language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:headless || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
env:
  global:
  - REPO_NAME=custom-ads-scheduler
  - OWNER_NAME=Brightspace
  - SAUCE_USERNAME: Desire2Learn
  # SAUCE_ACCESS_KEY
  - secure: qjK9sHvxsV9NdfhPsFw4BI98JynJazF+OLs+0NZPUXiQxulvyNpuEvtXTUnPhyilhIyIaRVG5L0l7dc4uBd/ml0q2u3znZ2o3KXzr2ZxDlKqqwBjUiI8fdIomOwU6qsy/RfUXU8JnQcVNFcNJVQaLeJ7ZdyyJ4pjB0GZS2Yw/xPbWK8l70GRVnpp7yPC9NkFoNRIvMj0bQBCZcYNBNct0ruPsKhMCDQiQYYJJa7j2lBrPgzve9Tl67tEj+LIiWxN6SD7nO7mktgpOVA4lOuK9KKkZ4ryg8/6QQFuRaOSlwBHEpUZkZcTvu3uLn1n5YyO4ZCvM1ZuVgCwWg/T2Eemeu+8b0L3uzjp2ebrFUGLF938CIyYJ6j3fy6AxHnMdZKtWBKx2C3ffsPZaKuHHja1TRvnTR0SUc9UEl3MUR60ENjQb+sVrk0R0HNIsEDTsWTwnW/pJF7ANtLDXPR+4lqs/aQ1LCP2dptMCmtB82Zj3wLmyvW5WrYH/g5LcNDo/qW1TbaezXHKqrlmjyv4tkNPbS3NZEITo8vqKGlKUOK3p6DleBd8/kS+QUHcbYSxTWjVlGyIrQFm5D2SyRxDwg3z9Cy6f5FTjB6gliWzWjxuoskxBD0CCy+TVVQ56GCLP5mCsYErpnY6K1btXjFNQlV8ATzMXQFxXciFALusTl5fYNI=
  # VISUAL_DIFF_S3_ID
  - secure: UX85TggO4e+iA3o/K70K+EYlWZ2I9Dcw37X2j1cZsCvmtobfEuy42/6rPmpPhiJ0vJalF1NUOpgMhvk9WfI3lWD7zuU+07t4pk4La4OqkLtyf05rRTJfdirzc2Hg/0oQmh8i5a43al3SZ1SZoAYv/Cm/v7RQl1VnfS/LB0XVjMMv/T4lakDWArahHn9szlQ8SdmhBi88h3WJHkWNzMzaVUGAe/t07WzUfwiw5Rwp0ULB94J6OXX2O8YjbDkI9jRynEjz3w3zKewZZtUtNoFFlWjz51NOd3fJXlciDNTx+YFx1G76Ebu0dbmUtdEwdM0vupre/tpceYIMwAET6H/PIfNbpF5djH9Lc5N4/yj80YU8CgpvFBwql0K1ep3RJUuRylYwKz1PMkmvFT6hNJixcXULAox31MmL6aC0z42fK3+lTjxIpAGutFsckVM41bq0O6ZqsJDenJgmR8Y27XjWj4dV+sOmujR8tIYL+jpafw98/o8qtnAcjU8uEEOu2Tyc8CaM/HxHITzVgv0QKHyfX2B3j5fiq5Zvceh/IEIf0Ev8VB7SvNa3jU77psRxGiNPcNHdpn3bcwgsBd5M/Qew+uVljL+HA+f21i3lUpZkI6/n23w2Lcy/wd6KRITCDPVJ9l1uzDXr7XviQywGbwkpGy21E7p2zCVNJZjQmEzWooo=
  # VISUAL_DIFF_S3_SECRET
  - secure: rnAY5Jz9HThhJE9Gh6bUhFS4USslrtz8zrcYWQ5DUfxlEVNsCMIza4kwBmppYjO8Tj/sCVG3X09p0yX1LHDjJA0xQVRRw9MmZ4dHg7YT6fgz+XrnJuTLhaQtTWjfOW0jUv2zS1wFEfbO/Rv/xtBepTIpgHaALCK46GCRAv7koGBlQEsxiRLZJ+qkDuagEiZCyXKp8mpaD0wYKjjBaDDDFn70sFCse9YceGttxEbPqGpt2MsHU90QXBgss3fKlSH9KVvyWivNRZmQFfR7pQcapKUYJk5Jvss2zPhy8bUaOg4wbJ+mnPHnGILJwNwRllA/mBMrjFSRuA8NXRLQK8mJMurQh1SbDpOXBguNFXWG3wtWlctG7YfFXqXqD/hfrjfLXOtCBI8kvh7RE2yLjkK+Xq9iu1zsYKHS6nUwRpMxw7y+F6sh4c2zP/eJR1lWxBxS6VTGAVe2YEch+x3cXvqAkRs1ChIy7/kd6Y2CqFe8ZoDVBiWGnecrylMUXWZRF/0txKC6kF7BzN4R6KwLDOiWdYnUD/KRDfZoJVbEfpFoDN7Q0VMGUfSFpxzRsGez/Gb2re5hdhbez5c6pzEdfDv/7GqbseTnAFqz1ECJqxPCE2c/xTH4JU0PGqrb3/iaYeFzOvGmtAXYrFeRX1hTVbZF2AvYRph8fiKwU2mH6qopWYQ=
